app/models.py
import enum

from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class UpdateType(enum.Enum):
    CCS_PUBLISHED = "Closed Case Summary Published"
    COMPLAINT_FILED = "Complaint Filed"
    INVESTIGATION_CLOSED = "Investigation Closed"


class Update(db.Model):
    __tablename__ = "updates"

    id = db.Column(db.Integer, nullable=False, primary_key=True)

    create_date = db.Column(db.DateTime, nullable=False)  # time of refresh
    event_date = db.Column(
        db.DateTime, nullable=False
    )  # time event happened (posted date etc)

    type = db.Column(db.Enum(UpdateType), nullable=False)
    officers = db.Column(db.JSON, nullable=False)  # Normalize as JSON
    allegations = db.Column(
        db.JSON, nullable=True
    )  # New complaints may not always have allegations
    url = db.Column(db.String, nullable=True)

    case_num = db.Column(db.String, nullable=False)
    disposition = db.Column(db.String, nullable=True)

    def to_dict(self):
        return {
            "id": self.id,
            "create_date": self.create_date,
            "event_date": self.event_date,
            "type": self.type.name,
            "officers": self.officers,
            "allegations": self.allegations,
            "url": self.url,
            "case_num": self.case_num,
            "disposition": self.disposition,
        }


class RefreshStatus(enum.Enum):
    STARTED = "Started"
    COMPLETED = "Completed"
    FAILED = "Failed"


class Refresh(db.Model):
    __tablename__ = "refreshes"
    id = db.Column(db.Integer, nullable=False, primary_key=True)
    status = db.Column(db.Enum(RefreshStatus), nullable=False)
    updates = db.Column(db.Integer, nullable=False, default=0)

    # Used to determine whether an update is needed
    refresh_date = db.Column(db.DateTime, nullable=False)

    # Latest event date seen for update type. Used in updater query to determine date after which to search for new entries
    closed_case_summary_last_updated = db.Column(db.DateTime, nullable=True)
    complaint_filed_last_updated = db.Column(db.DateTime, nullable=True)
    investigation_closed_last_updated = db.Column(db.DateTime, nullable=True)

    @staticmethod
    def last_refresh():
        return (
            Refresh.query.order_by(Refresh.refresh_date.desc()).limit(1).one_or_none()
        )

    @staticmethod
    def last_completed_refresh():
        return (
            Refresh.query.filter_by(status=RefreshStatus.COMPLETED)
            .order_by(Refresh.refresh_date.desc())
            .limit(1)
            .one_or_none()
        )

    def to_dict(self):
        return {
            "id": self.id,
            "refresh_date": self.refresh_date,
            "status": self.status.name,
        }

app/app.py
import logging

from flask import Flask

from app.config import config


def create_app(config_name="default"):
    app = Flask(__name__, static_folder="static", template_folder="templates")

    app.config.from_object(config[config_name])

    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True

    logging.basicConfig(
        filename=app.config["LOGGING_DIR"] / "application.log",
        level=logging.INFO,
    )

    with app.app_context():
        from .models import db

        db.init_app(app)

        db.create_all()

        from .views import views

        app.register_blueprint(views)

        return app

app/views.py
import re

from flask import (
    Blueprint,
    current_app,
    jsonify,
    make_response,
    render_template,
    request,
)

import app.updater as updater
from app.lookup import find_case
from app.models import Refresh, Update


views = Blueprint("app", __name__)


@views.before_request
def before():
    updater.update()


@views.route("/")
def index():
    return render_template("index.html")


@views.route("/refreshes")
def refreshes():
    page = request.args.get("page", 1, type=int)
    refreshes = Refresh.query.order_by(Refresh.refresh_date.desc())

    show_all = request.args.get("show_all")
    if not show_all:
        refreshes = refreshes.filter(Refresh.updates > 0)

    refreshes = refreshes.paginate(
        page=page, per_page=current_app.config["ITEMS_PER_PAGE"]
    )
    return render_template("refreshes.html", refreshes=refreshes, show_all=show_all)


@views.route("/refreshes.json")
def refreshes_json():
    refreshes = Refresh.query.all()
    return jsonify([refresh.to_dict() for refresh in refreshes])


@views.route("/updates")
def updates():
    # Pagination example: https://betterprogramming.pub/simple-flask-pagination-example-4190b12c2e2e
    page = request.args.get("page", 1, type=int)
    updates = Update.query.order_by(
        Update.create_date.desc(), Update.event_date.desc()
    ).paginate(page=page, per_page=current_app.config["ITEMS_PER_PAGE"])
    return render_template("updates.html", updates=updates)


@views.route("/updates.json")
def updates_json():
    updates = Update.query.all()  # TODO: trim to last 30 days?
    return jsonify([update.to_dict() for update in updates])


@views.route("/updates/<id>")
def update(id):
    update = Update.query.filter_by(id=id).one_or_none()
    if not update:
        return "Update not found", 404
    return render_template("update.html", update=update)


@views.route("/case")
def case():
    case_num = request.args.get("id", type=str)
    if not case_num or not re.match("^\\d{4}OPA-\\d{4}$", case_num):
        return "Invalid case number", 400

    result = find_case(case_num)
    if not result:
        return "Case not found", 404
    return render_template("case.html", case=result)


@views.route("/updates.xml")
def updates_atom():
    updates = Update.query.order_by(
        Update.create_date.desc(), Update.id.desc()
    ).all()  # TODO: trim to last 30 days?
    last_refresh = Refresh.last_refresh()

    resp = make_response(
        render_template(
            "updates.xml.j2",
            updates=updates,
            last_update=last_refresh.refresh_date,
            domain=current_app.config["DOMAIN"],
        )
    )
    resp.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    return resp


@views.route("/robots.txt")
def robots():
    return render_template("robots.txt")

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %} | SPD Data Watch</title>

    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <div class="container">
        <a class="navbar-brand" href="/">SPD Data Watch</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/refreshes">Refreshes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/updates">Updates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/updates.xml">Atom Feed</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

app/templates/case.html
{% extends "base.html" %}
{% block title %}{{case.case_num}}{% endblock %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="row"></th>
        <td><h3>{{case.case_num}}</h3></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="text-end" scope="row">Allegations</th>
        <td>
          <ul>
            {% for allegation in case.allegations %}
              <li>{{allegation}}</li>
            {% endfor %}
          </ul>
        </td>
      </tr>
      <tr>
        <th class="text-end" scope="row">Disposition</th>
        <td>{{case.disposition}}</td>
      </tr>
    </tbody>
  </table>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
  <form action="/case" method="get">
    <div class="mb-3">
      <label for="case-num" class="form-label"><h3>Case Lookup</h3></label>
      <input class="form-control" id="case-num" name="id" type="text" placeholder="OPA Case Number" />
    </div>

    <button class="btn btn-dark" type="submit">Lookup</button>
  </form>
{% endblock %}

app/templates/refreshes.html
{% extends "base.html" %}

{% block title %}Refreshes{% endblock %}

{% block content %}
  <h3>Refreshes</h3>

  <p>
    Refreshes indicate when we polled for updates from our data sources.
  </p>

  <form method="get">
      <input id="show_all" name="show_all" onclick="this.form.submit()" type="checkbox" {% if show_all %}checked {% endif %} />
      <label for="show_all">Include refreshes with zero updates</label>
  </form>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Status</th>
        <th scope="col">Updates</th>
        <th scope="col">Time</th>
      </tr>
    </thead>
    <tbody>
    {% for refresh in refreshes.items %}
      <tr{% if refresh.status.name == 'FAILED' %} class="table-secondary"{% endif %}>
        <td>{{ refresh.status.value }}</td>
        <td>{{ refresh.updates }}</td>
        <td>{{ refresh.refresh_date }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="my-3 text-center">
    <a href="{{ url_for('app.refreshes', page=refreshes.prev_num, show_all=show_all) }}" class="btn btn-sm btn-outline-dark {% if refreshes.page == 1 %}disabled{% endif %}">
        &larr;
    </a>
  {% for page_num in refreshes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if refreshes.page == page_num %}
      <a href="{{ url_for('app.refreshes', page=page_num, show_all=show_all) }}" class="btn btn-sm btn-dark">
        {{ page_num }}
      </a>
      {% else %}
      <a href="{{ url_for('app.refreshes', page=page_num, show_all=show_all) }}" class="btn btn-sm btn-outline-dark">
        {{ page_num }}
      </a>
      {% endif %}
    {% else %}
        ...
    {% endif %}
  {% endfor %}
    <a href="{{ url_for('app.refreshes', page=refreshes.next_num, show_all=show_all) }}" class="btn btn-sm btn-outline-dark {% if refreshes.page == refreshes.pages %}disabled{% endif %}">
        &rarr;
    </a>
  </div>
{% endblock %}

app/templates/update.html
{% extends "base.html" %}
{% from "update.j2" import render_update %}
{% block title %}Update{% endblock %}

{% block content %}
  {{ render_update(update) }}
{% endblock %}

app/templates/update.j2
{% macro render_update(update) %}
  <table class="table table-hover mt-3">
    <thead>
      <tr>
        <th></th>
        <td>
          <h3>New {{update.type.value}}</h3>
        </td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="text-end" scope="row">Case Number</th>
        <td>{{update.case_num}}</td>
      </tr>
      <tr>
        <th class="text-end" scope="row">Published</th>
        <td>{{update.event_date}}</td>
      </tr>
      <tr>
        <th class="text-end" scope="row">Allegations</th>
        <td>
          <ul>
          {% for allegation in update.allegations %}
            <li>{{allegation}}</li>
          {% endfor %}
          </ul>
        </td>
      </tr>
      <tr>
        <th class="text-end" scope="row">Disposition</th>
        <td>{{update.disposition}}</td>
      </tr>
    {% if update.type.name == 'CCS_PUBLISHED' %}
      <tr>
        <th class="text-end" scope="row">Link</th>
        <td><a class="text-secondary" href="{{update.url}}">{{update.url}}</a></td>
      </tr>
    {% endif %}
    </tbody>
  </table>
{% endmacro %}

app/templates/updates.html
{% extends "base.html" %}
{% block title %}Updates{% endblock %}

{% block content %}
  <h3>Updates</h3>

  <p>
    Updates are events we are watching for in our data sources.
  </p>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Case Number</th>
        <th scope="col">Type</th>
        <th scope="col">Time</th>
      </tr>
    </thead>
    <tbody>
    {% for update in updates.items %}
      <tr>
        <td><a class="text-secondary" href="/updates/{{ update.id }}">{{ update.case_num }}</a></td>
        <td>{{ update.type.value }}</td>
        <td>{{ update.event_date }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="my-3 text-center">
    <a href="{{ url_for('app.updates', page=updates.prev_num) }}" class="btn btn-sm btn-outline-dark {% if updates.page == 1 %}disabled{% endif %}">
        &larr;
    </a>
  {% for page_num in updates.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if updates.page == page_num %}
      <a href="{{ url_for('app.updates', page=page_num) }}" class="btn btn-sm btn-dark">
        {{ page_num }}
      </a>
      {% else %}
      <a href="{{ url_for('app.updates', page=page_num) }}" class="btn btn-sm btn-outline-dark">
        {{ page_num }}
      </a>
      {% endif %}
    {% else %}
        ...
    {% endif %}
  {% endfor %}
    <a href="{{ url_for('app.updates', page=updates.next_num) }}" class="btn btn-sm btn-outline-dark {% if updates.page == updates.pages %}disabled{% endif %}">
        &rarr;
    </a>
  </div>
{% endblock %}

app/templates/updates.xml.j2
{% from "update.j2" import render_update %}
<?xml version="1.0" encoding="utf-8"?>

<feed xmlns="http://www.w3.org/2005/Atom">
  <title>SPD Data Watch Feed</title>
  <subtitle>Updates from various SPD open data sources</subtitle>
  <updated>{{last_update.replace(microsecond=0).isoformat('T')}}Z</updated>

  <id>{{domain}}/updates.xml</id>

  {% for update in updates %}
  <entry>
    <id>{{domain}}/updates/{{update.id}}</id>
    <link href="{{domain}}/updates/{{update.id}}" />
    <author>
      <name>robot</name>
    </author>

    <title>New {{update.type.value}}: {{update.case_num}}</title>
    <published>{{update.create_date.replace(microsecond=0).isoformat('T')}}Z</published>
    <updated>{{update.create_date.replace(microsecond=0).isoformat('T')}}Z</updated>

    <content type="xhtml">
      <div xmlns="http://www.w3.org/1999/xhtml">
        {{ render_update(update) }}
      </div>
    </content>
  </entry>
  {% endfor %}
</feed>